name: The Alex Nicoll Experience
favicon: null
layout_spectrum: 0.9489796
typography_spectrum: 0.13574
title: The Alex Nicoll Experience
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1F21'
    - '#E6EAE9'
    - '#51504C'
    - '#DE587D'
    - '#288287'
  brandStrength: 1
  lightness: 0.7696025
  saturation: 0.375
  rhythmicContrast: 0.5844181
purpose: []
