name: The Alex Nicoll Experience
favicon: null
layout_spectrum: 0.57354
typography_spectrum: 0.13574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8a680'
    - '#e95832'
    - '#edddc3'
    - '#2c2c24'
    - '#a1533a'
  brandStrength: 0.875
  lightness: 0.31028123502619565
  saturation: 0.375
  rhythmicContrast: 0.5844180586282164
purpose: []
