title: The Alex Nicoll Experience
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.375
  brandStrength: 1
  lightness: 0.7696025
  brandColors:
    - '#b8a680'
    - '#e95832'
    - '#edddc3'
    - '#2c2c24'
    - '#a1533a'
  rhythmicContrast: 0.5844181
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: The Alex Nicoll Experience
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.13574
layout_spectrum: 0.57354
